all: bitacora standard

bitacora: bitacora.tex
	pdflatex bitacora.tex
	pdflatex bitacora.tex
	pdflatex bitacora.tex


standard: standard.tex
	pdflatex standard.tex
	pdflatex standard.tex
	pdflatex standard.tex

clean:
	rm -rf *.pdf *.log *.aux *.lof *.out *.toc *.lot *.bbl *.db *.blg

